### ISSUE TITLE
support for CRS with units of feet

### ISSUE THREAD

**Issue by aleaf** [aleaf/modflow-setup#18]
Currently, coordinate references systems are assumed to be in meters, but cooperators may often have a preferred CRS with units of feet (for example [EPSG:4456](http://epsg.io/4456-8613)). For such CRS to work with modflow-setup, we need to make it aware of the CRS length units. The `MFsetupGrid` grid class, which inherits from Flopy's `StructuredGrid`, assumes that delr and delc are input in the length units of the CRS (i.e. it does not convert length units or maintain separate grids for the CRS vs. the model coordinate system). So to solve this we probably need to detect the units of the CRS with something like this:

```python
units = <pyproj.crs instance>.axis_info[0].unit_name
               translate_units = {'metre': 'meters'}
               crs_units = translate_units.get(units, units)
```
and then replace the unit conversion statement in` grid.setup_structured_grid` with something like this:

to_crs_units = convert_length_units(model_length_units, crs_units)

it might also be useful to add a length_units property to `MFsetupGrid` that returns 'meters' or 'feet', etc.

@mnfienen

**Comment by mnfienen** [comment]
@aleaf I believe we got this working along with the rotation support.

**Comment by aleaf** [comment]
yeah, wanted to add a test though to make sure the unit handling was robust; ended up doing some more refactoring and delegation of CRS handling to pyproj.CRS. Should hopefully be settled now with b77d1ef.
