### ISSUE TITLE
minor plumbing issue in example

### ISSUE THREAD

**Issue by wkitlasten** [aleaf/modflow-setup#26]
Sorry, probably silly, but:

from mfsetup import MF6model

gives:

ModuleNotFoundError: No module named 'mfsetup'

Unless I move the mfsetup dir into the examples dir. Is that the intention? I'm not smurt enuf to figure out how to import from 1 directory up!

**Comment by aleaf** [comment]
hi @wkitlasten, are you working in an environment where modflow-setup is installed? More info in the [Installation section](https://aleaf.github.io/modflow-setup/latest/installation.html#) of the docs.

**Comment by wkitlasten** [comment]
I was following [Contributing to modflow-setup](https://aleaf.github.io/modflow-setup/latest/contributing.html#contributing-to-modflow-setup) (I will try not to cause too many headaches!). But alas, I missed the "pip install -e ." step, doh.

btw, a couple issues I had on the page mentioned above:

`conda env create -f environment-dev.yml `

is now(?):

`conda env create -f requirements-dev.yml`

and I believe in that file:

`- gis-utils`

needs to be under `pip:` (at least that's how it worked for me)

Also:

`python install -e .`

should be:

`pip install -e .`

**Comment by aleaf** [comment]
@wkitlasten thanks for catching these! Should be fixed with 83489af0633784d87c018737eeba32d8f26201a8. Let me know if you find anything else or feel free to PR if you're so inspired.
