### ISSUE TITLE
idomain with shapefile

### ISSUE THREAD

**Issue by wkitlasten** [aleaf/modflow-setup#27]
I am trying to specify a new active domain in the pleasant example using a shapefile. I have created a shapefile with a single field named "idomain" which has the integer value 1. I added the following to the "source_data" sub-block of the "dis" package of "pleasant_lgr_parent.yml". The ibound arrays ("examples\pleasant_lgr\external\plsnt_lgr_parent_idomain_***.dat") don't reflect the new idomain I would like from the shapefile.

Am I missing something obvious? 

```
dis:
  .
  .
  source_data:
    .
    .
    idomain_shapefile:
        filenames: 
          1: 'data/pleasant/source_data/shps/myshape.shp'
          2: 'data/pleasant/source_data/shps/myshape.shp'
          3: 'data/pleasant/source_data/shps/myshape.shp'
          4: 'data/pleasant/source_data/shps/myshape.shp'
        id_columns: 
          1: 'idomain'
          2: 'idomain'
          3: 'idomain'
          4: 'idomain'
        include_ids: 1
```

I also tried the simpler:

```
dis:
  .
  .
  source_data:
    .
    .
    idomain_shapefile:
        filename:  'data/pleasant/source_data/shps/myshape.shp'
        id_column: 'idomain'
        include_ids: 1
```

I also tried dropping id_columns and include_ids. Which begs the question, am I missing an obvious log file that is telling me I messed something up?

**Comment by aleaf** [comment]
Hi @wkitlasten did you try using ``idomain`` instead of ``idomain_shapefile``:
```python
dis:
  .
  .
  source_data:
    .
    .
    idomain:
      filename: 'data/pleasant/source_data/shps/myshape.shp'
      id_column: 'idomain'
      include_ids: 1
```
I think specifying a separate shapefile for each layer should also work, but you would be limited to a single set of ``id_column`` and ``include_ids`` arguments.
```python
    idomain:
      filenames: 
        0: 'data/pleasant/source_data/shps/myshape1.shp'
        1: 'data/pleasant/source_data/shps/myshape2.shp'
        ...
      id_column: 'idomain'
      include_ids: 1
```

**Comment by aleaf** [comment]
Note that this software is in really early development (not even at version 0.1 yet), so the feature support isn't comprehensive, and the interface also a little unsettled. If you have suggestions for improving either, please post an issue!

**Comment by wkitlasten** [comment]
@aleaf , I tried the idomain as you wrote it (+/- "id_column", "id_columns", "include_ids", "include_id"), but it still didn't change the idomain file (no warnings... silently finished the example without issue). In QGIS I set epsg to 3070 for both botm0 and myshape to make sure everything was in the right place, and now I am getting:

```
c:\users\wesk\documents\git\modflow-setup-wkitlasten\mfsetup\grid.py in rasterize(feature, grid, id_column, include_ids, crs, epsg, proj4, dtype, **kwargs)
    622                                 out_shape=(grid.nrow, grid.ncol),
    623                                 transform=trans)
--> 624     assert result.sum(axis=(0, 1)) != 0, "Nothing was intersected!"
    625     return result.astype(dtype)
    626 

AssertionError: Nothing was intersected!
```

I'm happy to see new error messages because it means things are changing... but I'm a bit confused how neglecting to set the epsg in the first round didn't give me the "Nothing was intersected" error given myshape could have been anywhere.

I appreciate that modflow-setup is in early development. It is a super cool concept and I hope to use it without causing too many issues for you (fair warning, if it can be broken/done wrong I will probably do it). I will keep troubleshooting.

Here is a screenshot if anything stands out as obviously wrong, please let me know.

![image](https://user-images.githubusercontent.com/14982084/109065482-8658fd00-7750-11eb-907b-dc653824b34c.png)

**Comment by wkitlasten** [comment]
Hey, entirely on my end. Apparently I messed up the shapefile early on. The following works fine (assuming there are no 'inf' in the geometry):

```
idomain:
      filename: 'data/pleasant/source_data/shps/myshape.shp'
      id_column: 'idomain'
      include_ids: 1
```
