### ISSUE TITLE
LGR Parent not creating a name file

### ISSUE THREAD

**Issue by mnfienen-usgs** [aleaf/modflow-setup#4]
I'm running into a challenge where running modflow setup with LGR is coming on trying to load the LGR parent name file at line 96 of utils: `with open(namefile) as src:` called from `set_parent` on line 847 of mfmodel.py. I will try to debug but wanted to see if this is a known issue. Result is total crash so the inset cannot be made. (btw - this is plainfield/pleasant....)

**Comment by aleaf** [comment]
I think this should be fixed now by 59addcbaf6dd33af.

**Comment by mnfienen-usgs** [comment]
Thanks @aleaf ! I confirmed that it worked on my problems. Thanks!
