### ISSUE TITLE
feature needed: implement irch array

### ISSUE THREAD

**Issue by aleaf** [aleaf/modflow-setup#8]
We need modflow-setup to compute an `irch` array indicating the highest active cell at each `i, j` location where recharge should be applied, and then include that as an external file argument to `flopy`, so that `irch` gets included in the modflow-6 recharge array input. Outline of a possible approach include irch:

* add a `make_irch` function to `mfsetup.discretization.py` that accepts a 3D numpy array of `idomain`, and returns a 2D numpy array of `irch`
* to `setup_rch` add the a call to the `_setup_array()` method (prior to making the keyword arguments for flopy input): 
```python
irch = make_irch(self.idomain)
self._setup_array('rch', 'irch',
                          data={0: irch},
                          datatype='array2d', 
                          write_fmt='%d', dtype=int)

```
* the above method should result in the external array text file for `irch` being written and added to the configuration dictionary (and therefore the keyword input to flopy, but want to confirm this is the case
* then to `MF6model._set_idomain()` add another call to `_setup_array()`, and reassign it to the dis package attribute
```python
irch = make_irch(self.idomain)
self._setup_array('rch', 'irch',
                          data={0: irch},
                          datatype='array2d', 
                          write_fmt='%d', dtype=int)
self.dis.irch = self.cfg['dis']['irch']
```
* this should cause the irch array to be recomputed and refreshed in the dis package instance each time the idomain array is recomputed

**Comment by mnfienen** [comment]
I created a `make_irch` function in `discretization.py`. When I try to call it in `MF6model._set_idomain()` it fails though I think because trying to call `_setup_array()` for the 'rch' package prior to it being created is not possible (maybe? It's failing in the setting up of external paths). 

You can see how far I got at: [my feature branch](https://github.com/mnfienen/modflow-setup/tree/feat_irch)

**Comment by aleaf** [comment]
added with 71b3a88d
